# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('insur_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='RiskTypeAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Risk Attribute Name')),
                ('display', models.CharField(blank=True, max_length=64, null=True, verbose_name='Attribute Label')),
                ('attribute_type', models.CharField(choices=[('t', 'Text'), ('i', 'Integer'), ('b', 'Boolean (Yes/No)'), ('s', 'Dropdown Choices'), ('d', 'Date')], default='t', max_length=1, verbose_name='Attribute type')),
                ('default_value', models.IntegerField(blank=True, max_length=1024, null=True, verbose_name='attribute default value')),
                ('is_required', models.BooleanField(default=False, verbose_name='Required')),
                ('field_choices', models.CharField(blank=True, help_text='List the choices want to displayed, comman delimited', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'Risk Attributes',
            },
        ),
        migrations.CreateModel(
            name='RiskTypeAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Attribute value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_value', to='risks.RiskTypeAttribute', verbose_name='Risk Attribute')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Risk', verbose_name='Risk')),
            ],
        ),
        migrations.CreateModel(
            name='RiskTypeEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Risk Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name_plural': 'Risk Type',
            },
        ),
        migrations.AddField(
            model_name='risktypeattribute',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.RiskTypeEntity', verbose_name='Risk Type'),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.RiskTypeEntity', verbose_name='Risk Type'),
        ),
        migrations.AlterUniqueTogether(
            name='risktypeentity',
            unique_together=set([('company', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='risktypeattribute',
            unique_together=set([('risk_type', 'name')]),
        ),
    ]
