# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktypeattribute',
            name='default_value',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='attribute default value'),
        ),
    ]
