# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-03 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20180203_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risk',
            options={'verbose_name_plural': 'Risk'},
        ),
        migrations.AlterModelOptions(
            name='risktypeattribute',
            options={'verbose_name_plural': 'Risk Type Attributes'},
        ),
        migrations.AlterField(
            model_name='risk',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='risktypeentity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Risk Type Name'),
        ),
    ]
